server {
    listen 443 ssl;
    server_name localhost;
    # we need the signed certification for HTTPS  both the self-signed and key
    # self signed cetif is sent to the client it containes also the public key ( signed with the server public key)
    ssl_certificate /etc/nginx/ssl/self-signed.crt;
    # key is the private key 
    ssl_certificate_key /etc/nginx/ssl/self-signed.key;
    # forcing to use the lattest TLS versions
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}

server {
    # redirecting http traffic to https
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}
