[www]
user = nobody
group = nobody

; only thing you need to change 
listen = 0.0.0.0:9000

; working process , this part kinda similar to how nginx works ( with the working processes)
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

clear_env = no   ; keep this too - so wordpress can read your env vars